CREATE TABLE `controls` ( `ID` , `DESCRIPTION` , `GUIDANCE` , `PRIORITY` )
CREATE TABLE "detailedthreats" ( `ID` , `Summary` )
CREATE TABLE `features` ( `ID` INTEGER PRIMARY KEY AUTOINCREMENT, `Description` INTEGER, PRIMARY KEY(`ID`) )
CREATE TABLE "projects" ( `ID` INTEGER PRIMARY KEY AUTOINCREMENT, 'Name' TEXT, 'TestPeriod' TEXT, 'Owner' TEXT, 'Contact' TEXT, 'Reviewer' TEXT, 'Classification' TEXT, 'Repositories' TEXT, 'Endpoints' TEXT )
CREATE TABLE `finding` ( `ID` INTEGER PRIMARY KEY AUTOINCREMENT, `Description` TEXT, `Impact` TEXT, `Recommendation` TEXT, `Cvss` REAL, `RemediationEffort` INTEGER, `Vector` TEXT, `Rating` INTEGER )